# Generated by Django 5.0 on 2023-12-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('hostname', models.CharField(max_length=100)),
                ('syslog', models.BooleanField()),
                ('web_access', models.BooleanField()),
                ('ssh', models.BooleanField()),
                ('snmp', models.BooleanField()),
                ('users', models.BooleanField()),
                ('ntp', models.BooleanField()),
                ('no_telnet', models.BooleanField()),
                ('inactivity', models.BooleanField()),
                ('interfaces', models.BooleanField()),
                ('protocols', models.BooleanField()),
                ('policies', models.BooleanField()),
            ],
        ),
    ]
